-- Seed: 15 investiții publice din bugetul municipal Cluj-Napoca 2026
-- Rulează după migrations/0001_schema.sql

DELETE FROM projects;

INSERT INTO projects (
  id,
  name,
  description_original,
  status,
  category,
  budget_ron,
  budget_source,
  responsible_institution,
  location_lat,
  location_lng,
  address,
  district,
  start_date,
  end_date,
  source_url,
  source_type
) VALUES
(
  'pasarela-manastur-2026',
  'Pasarela pietonală Mănăștur',
  'Obiectiv de investiții aprobat prin HCL nr. 245/2025 privind bugetul local pe anul 2026. Realizarea unei pasarele pietonale și cicliste deasupra șoselei de centură, în zona nodului Mănăștur, pentru creșterea siguranței traversării și conectarea cartierului la rețeaua de transport public. Documentația tehnică este aprobată; lucrările de execuție sunt în derulare conform graficului de șantier.',
  'continuing',
  'mobility',
  18500000,
  'mixed',
  'Primăria Municipiului Cluj-Napoca',
  46.7498,
  23.5521,
  'Strada Mănăștur, zona nod rutier',
  'Mănăștur',
  '2025-06-01',
  '2026-12-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'rehab-observatorului-2026',
  'Reabilitare str. Observatorului',
  'Proiect cuprins în Programul anual de lucrări publice 2026. Modernizarea carosabilului, a trotuarelor și a rețelelor subterane pe tronsonul străzii Observatorului, între Bulevardul Muncii și strada Louis Pasteur, cu respectarea normativelor de accesibilitate și iluminat public LED. Faza de organizare de șantier și demolări ușoare a fost demarată în T1 2026.',
  'starting',
  'mobility',
  9200000,
  'local',
  'Primăria Municipiului Cluj-Napoca',
  46.7685,
  23.5892,
  'Strada Observatorului',
  'Mărăști',
  '2026-03-01',
  '2027-08-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'piste-floresti-2026',
  'Extindere rețea piste ciclabile Florești',
  'Investiție transfrontalieră în parteneriat cu Comuna Florești, finanțată din bugetul municipiului Cluj-Napoca și cofinanțare locală. Extinderea rețelei de piste biciclete pe coridoarele de legătură spre cartierul Grigorescu și zona metropolitană Florești, conform Studiului de circulație aprobat. Procedura de achiziție publică pentru proiectare și execuție este în curs de desfășurare.',
  'procurement',
  'mobility',
  6800000,
  'mixed',
  'Primăria Municipiului Cluj-Napoca',
  46.7425,
  23.5018,
  'Strada Eroilor, zona limită Florești',
  'Grigorescu',
  '2026-05-01',
  '2028-06-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'piata-mihai-viteazu-2026',
  'Modernizare Piața Mihai Viteazu',
  'Obiectiv prioritar de regenerare urbană în centrul istoric. Reamenajarea pieței: pavaj antiderapant, mobilier urban, zone verzi, rețele edilitare și iluminat arhitectural, cu avizele Comisiei Zonală Monumente Istirice obținute. Execuția lucrărilor se apropie de finalizare; recepția parțială este programată pentru trimestrul II 2026.',
  'finalizing',
  'cultural',
  22400000,
  'european',
  'Primăria Municipiului Cluj-Napoca',
  46.7709,
  23.5887,
  'Piața Mihai Viteazu',
  'Centru',
  '2024-09-15',
  '2026-06-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'scoala-11-rehab-2026',
  'Reabilitare Școala nr. 11',
  'Investiție în infrastructura educațională publică, aprobată prin bugetul local 2026. Reabilitarea termică și energetică a clădirii Școlii Gimnaziale nr. 11, înlocuirea ferestrelor, modernizarea instalațiilor și adaptarea sălilor la standardele actuale de siguranță la incendiu. Contractul de execuție este în derulare, cu monitorizare lunară de către Direcția Educație.',
  'continuing',
  'education',
  4500000,
  'national',
  'Primăria Municipiului Cluj-Napoca',
  46.7642,
  23.5815,
  'Strada Clinicilor nr. 14',
  'Centru',
  '2025-11-01',
  '2026-10-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'parc-fotovoltaic-dezmir-2026',
  'Parc fotovoltaic Dezmir',
  'Proiect de energie regenerabilă pe teren aparținând domeniului public, în extravilanul Dezmir. Instalarea unui parc fotovoltaic cu putere instalată estimată de 4 MW, conform avizelor de mediu și a studiului de fezabilitate energetică. Se derulează procedura de achiziție pentru proiectant și antreprenor general.',
  'procurement',
  'energy',
  31200000,
  'european',
  'Primăria Municipiului Cluj-Napoca',
  46.7812,
  23.6985,
  'Șoseaua Dezmir, perimetru parc solar',
  'Dezmir',
  '2026-07-01',
  '2028-12-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'metrou-cluj-l1-2026',
  'Extindere metrou Cluj linie 1',
  'Proiect strategic de transport public în masă, aflat în faza de planificare și pregătire documentație pentru finanțare europeană. Linia 1 — coridor Est–Vest: studii de trafic, aliniament preliminar și proceduri de expropriere/uzucapiune conform HG privind metroul din Cluj-Napoca. Alocare bugetară 2026 pentru studii și consultanță tehnică.',
  'planned',
  'mobility',
  50000000,
  'mixed',
  'Primăria Municipiului Cluj-Napoca',
  46.7710,
  23.5860,
  'Bulevardul Eroilor — coridor metrou',
  'Centru',
  '2026-01-01',
  '2035-12-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'rehab-termica-bloc-fond-2026',
  'Reabilitare termică bloc fond',
  'Program municipal de eficiență energetică în fondul locativ construit înainte de 1990. Reabilitarea termică a ansamblului de blocuri din cartierul Mărăști (lot 3), cu termoizolație fațade, înlocuire instalații comune și finanțare prin Programul Național de Renovare. Lucrările sunt în execuție pe 6 blocuri din 9 programate.',
  'continuing',
  'housing',
  15800000,
  'national',
  'Primăria Municipiului Cluj-Napoca',
  46.7545,
  23.6210,
  'Strada Bucium, ansamblu blocuri',
  'Mărăști',
  '2025-04-01',
  '2026-11-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'iluminat-marasti-2026',
  'Modernizare iluminat public Mărăști',
  'Înlocuirea corpurilor de iluminat cu tehnologie LED și implementarea sistemului de management inteligent al iluminatului public în cartierul Mărăști. Proiect aprobat în bugetul 2026; recepția pe sectoare este în curs, cu reducere estimată a consumului de 42%.',
  'finalizing',
  'energy',
  3200000,
  'local',
  'Primăria Municipiului Cluj-Napoca',
  46.7538,
  23.6245,
  'Cartier Mărăști — rețea iluminat public',
  'Mărăști',
  '2025-08-01',
  '2026-05-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'centru-social-gheorgheni-2026',
  'Centru social Gheorgheni',
  'Construcția unui centru multifuncțional de servicii sociale pentru vârstnici și familii vulnerabile, în cartierul Gheorgheni. Proiectul beneficiază de autorizație de construire; lucrările de fundație și structură au fost demarate în februarie 2026.',
  'starting',
  'social',
  11200000,
  'mixed',
  'Primăria Municipiului Cluj-Napoca',
  46.7455,
  23.6058,
  'Strada Nicolae Bălcescu, Gheorgheni',
  'Gheorgheni',
  '2026-02-01',
  '2027-06-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'parc-central-rehab-2026',
  'Reabilitare Parcul Central',
  'Reabilitarea Parcului Central „Simion Bărnuțiu”: alei, mobilier, sistem de irigații, zone de joacă și iluminat, conform proiectului tehnic aprobat. Execuția este în faza finală; predarea către administrația domeniului public este planificată pentru vara 2026.',
  'finalizing',
  'green',
  8900000,
  'local',
  'Primăria Municipiului Cluj-Napoca',
  46.7662,
  23.5821,
  'Parcul Central Simion Bărnuțiu',
  'Centru',
  '2024-06-01',
  '2026-07-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'statie-epurare-2026',
  'Modernizare stație epurare',
  'Modernizarea liniei tehnologice și a echipamentelor la Stația de Epurare a Apelor Uzate Cluj-Napoca, pentru conformare la directivele europene și creșterea capacității de tratare. Contract de execuție în derulare, cu etape de probe tehnologice programate trimestrial.',
  'continuing',
  'waste',
  38500000,
  'european',
  'Compania de Apă Someș S.A.',
  46.7725,
  23.5680,
  'Strada Ștrandului — STA Cluj',
  'Centru',
  '2025-01-15',
  '2027-12-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'retea-transport-electric-2026',
  'Extindere rețea transport electric',
  'Extinderea rețelei de troleibuz și tramvai și achiziția de vehicule cu emisii zero pe coridoarele principale, în cadrul strategiei de mobilitate urbană durabilă. Demararea lucrărilor la depouri și la linia de contact pe Bulevardul Muncii în T1 2026.',
  'starting',
  'mobility',
  24600000,
  'european',
  'Primăria Municipiului Cluj-Napoca',
  46.7678,
  23.5925,
  'Bulevardul Muncii — coridor transport electric',
  'Mărăști',
  '2026-01-15',
  '2028-03-31',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'patrimoniu-piata-unirii-2026',
  'Reabilitare patrimoniu Piața Unirii',
  'Conservarea și reabilitarea fațadelor și a elementelor de patrimoniu din perimetrul Pieței Unirii, cu avizele Ministerului Culturii. Proiect în fază de documentație și licitație design, alocare bugetară 2026 pentru studii și proiectare.',
  'planned',
  'cultural',
  7600000,
  'mixed',
  'Primăria Municipiului Cluj-Napoca',
  46.7713,
  23.5889,
  'Piața Unirii',
  'Centru',
  '2026-09-01',
  '2029-06-30',
  'https://www.primariaclujnapoca.ro',
  'webpage'
),
(
  'gradinita-zorilor-2026',
  'Construire creșă Zorilor',
  'Construcția unei creșe noi cu 120 de locuri în cartierul Zorilor, pentru reducerea listelor de așteptare la unitățile de învățământ preșcolar. Procedura de achiziție pentru execuție este în evaluare; amplasament: strada Pasteur, parcelă aprobată prin CU.',
  'procurement',
  'social',
  9800000,
  'local',
  'Primăria Municipiului Cluj-Napoca',
  46.7635,
  23.5748,
  'Strada Louis Pasteur, Zorilor',
  'Zorilor',
  '2026-04-01',
  '2027-12-15',
  'https://www.primariaclujnapoca.ro',
  'webpage'
);
