-- Seed: same 6 projects as former lib/projects.ts
INSERT INTO projects (
  id, title, description, category, status, budget, funding_source,
  lng, lat, start_date, planned_end_date, progress_percent, is_delayed
) VALUES
(
  'horea-rehab',
  'Reabilitare Strada Horea',
  'Modernizarea carosabilului și a trotuarelor pe tronsonul dintre străzile Avram Iancu și Bulevardul Eroilor. Include iluminat LED, rețele subterane și benzi dedicate bicicliștilor.',
  'Infrastructură rutieră',
  'În lucru',
  12450000,
  'Fonduri Europene (POR)',
  23.5872,
  46.7718,
  '2024-03-15',
  '2025-11-30',
  62,
  1
),
(
  'piata-unirii',
  'Reamenajare Piața Unirii',
  'Proiect de revitalizare a pieței centrale: pavaj nou, mobilier urban, zone pietonale extinse și accesibilitate pentru persoane cu dizabilități. Faza de execuție urmează după finalizarea licitației.',
  'Infrastructură rutieră',
  'Bugetat',
  28300000,
  'Buget local + PNRR',
  23.5889,
  46.7713,
  '2025-09-01',
  '2027-06-30',
  18,
  0
),
(
  'tramvai-marasti',
  'Extindere linie tramvai — cartier Mărăști',
  'Studiu de fezabilitate și proiect tehnic pentru prelungirea liniei de tramvai spre cartierul Mărăști, cu stații noi la intersecțiile principale. Etapa curentă: consultări publice și avize urbanistice.',
  'Transport public',
  'Inițiat',
  95000000,
  'Fonduri Europene (ITI)',
  23.6254,
  46.7548,
  '2025-01-10',
  '2028-12-31',
  8,
  0
),
(
  'somes-promenada',
  'Promenadă pe malul Someșului',
  'Amenajarea unui traseu pietonal și ciclist de-a lungul malului Someșului Mic, între Podul Elisabeta și Parcul Feroviarilor. Include zone de odihnă și plantări noi.',
  'Parcuri și spații verzi',
  'Finalizat',
  6780000,
  'Buget local',
  23.5748,
  46.7681,
  '2023-04-01',
  '2025-10-15',
  100,
  0
),
(
  'parcul-central',
  'Reabilitare Parcul Central „Simion Bărnuțiu”',
  'Renovarea aleilor, a sistemului de irigații și a zonei de joacă din Parcul Central. Proiectul a fost aprobat, dar execuția a fost amânată din cauza procedurilor de achiziție.',
  'Parcuri și spații verzi',
  'Aprobat',
  4200000,
  'Buget local',
  23.5821,
  46.7662,
  '2024-06-01',
  '2025-08-31',
  25,
  1
),
(
  'campus-memorandumului',
  'Extindere campus universitar — Strada Memorandumului',
  'Construcția unei clădiri noi pentru laboratoare și săli de curs la Universitatea Tehnică, cu eficiență energetică ridicată. Lucrările de fundație sunt în desfășurare.',
  'Educație',
  'În lucru',
  42500000,
  'Fonduri Europene (POR) + cofinanțare locală',
  23.5915,
  46.7694,
  '2024-11-01',
  '2026-09-30',
  48,
  0
);
